If we run this function with an argument of "Fail",