When the test fails, we move on to the code below the loop.